language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "kAQe+t74Naflzwf3KZfw9/re6P1k59C5y6+pBL+vyK/tFsGcVddd9V9OqMLI4QNtwEZePQ5rIb4O6uM0KBd521xdg6hr9RGllImZbCJKlQKcQXzIhFmla0PsHQ4S3K2b3KsOuPdGRbMzry02cJnScpy21BD5IN2HgcRHAA7QYy+0wgxTZ7PR2nN4Zm6qBGAuh/M4FTncFphLkjAlf/xRxxsK3BVu7RenadOQBXUC/DKHwPM5X261kVcPYTtZ6alfPsG1HfHLfPia1nXZ/DN0DfILxFA2pjODu3QJf0PiEfZQ9l0FrGKEyXjD2us5epDK5s9S404JC2eLt8VuvCEv27uws4YhnQxIRYb5wt8Z4ex1c5W2k3qaQievvk+TKjKuJYxOPE0vkE/K2waD2/FFgwB40olv4zTvRGCI9v5OwAODhKfmH4TFEYfmnCj7oZZjMaaddBBYpXhvGBAyWQ7Ld1FRQS1t4s1pu5hdkuCVLN8WTZtUM6M3MdrUhiuFyfuUK/XDPg+mhAXciCp62SmtJtgd8gZ6txY0Z30elbfhT+bHFULSKJq/WAju5UXS3nLwJ0+wtSTq9mspzVUZN+GRMe4E4FtHHCy7Cd1G41ilKKn6Or7zwyQYrePvR/clL2FtbAsQCSjdcScai9lc64s8pyYw6ocEI4FdhC14DLQKOsw="
